select max(cohort.patienthealthsystemstayid) as patienthealthsystemstayid,
       max(cohort.gender) as gender,
       max(cohort.age) as age,
       max(cohort.ethnicity) as ethnicity,
       max(cohort.hospitalid) as hospitalid,
       max(cohort.wardid) as wardid,
       max(cohort.apacheadmissiondx) as apacheadmissiondx,
       max(cohort.admissionheight) as admissionheight,
       max(cohort.hospitaladmittime24) as hospitaladmittime24,
       max(cohort.hospitaladmitoffset) as hospitaladmitoffset,
       max(cohort.hospitaladmitsource) as hospitaladmitsource,
       max(cohort.hospitaldischargeyear) as hospitaldischargeyear,
       max(cohort.hospitaldischargetime24) as hospitaldischargetime24, 
       max(cohort.hospitaldischargeoffset) as hospitaldischargeoffset,
       max(cohort.hospitaldischargelocation) as hospitaldischargelocation,
       max(cohort.hospitaldischargestatus) as hospitaldischargestatus,
       max(cohort.unittype) as unittype,
       max(cohort.unitadmittime24) as unitadmittime24,	
       max(cohort.unitadmitsource) as unitadmitsource,
       max(cohort.unitvisitnumber) as unitvisitnumber,
       max(cohort.unitstaytype) as unitstaytype,
       max(cohort.admissionweight) as admissionweight,
       max(cohort.dischargeweight) as dischargeweight,
       max(cohort.unitdischargetime24) as unitdischargetime24,
       max(cohort.unitdischargeoffset) as unitdischargeoffset,
       max(cohort.unitdischargelocation) as unitdischargelocation,
       max(cohort.unitdischargestatus) as unitdischargestatus,
       max(cohort.uniquepid) as uniquepid,
       max(cohort.teachingstatus) as teachingstatus,
       max(cohort.region) as region,
       max(cohort.apachedxgroup) as apachedxgroup,
       max(cohort.gcs) as gcs,
       max(cohort.gcs_motor) as gcs_motor,
       max(cohort.gcs_eyes) as gcs_eyes,
         max(cohort.gcs_verbal),
         max(cohort.delirium_scale),
         max(cohort.delirium_score),
         max(cohort.sedation_scale),
         max(cohort.sedation_score),
         max(cohort.sedation_goal),
         max(cohort.pain_score),
         max(cohort.drugoffset),
         max(cohort.drugenteredoffset),
         max(cohort.drugnotetype),
         max(cohort.admission_drug_name),
         max(cohort.apache_iv),
         max(cohort.icu_los_hours),
         max(cohort.dopamine),
         max(cohort.dobutamine),
         max(cohort.norepinephrine),
         max(cohort.phenylephrine),
         max(cohort.epinephrine),
         max(cohort.vasopressin),
         max(cohort.milrinone),
         max(cohort.heparin),
         max(cohort.fio2),
         max(cohort.pao2),
         max(cohort.paco2),
         max(cohort.pH),
         max(cohort.aniongap),
         max(cohort.basedeficit),
         max(cohort.baseexcess),
         max(cohort.peep),
         max(cohort.apacheScore),
         max(cohort.acutePhysiologyScore),
         max(cohort.apacheVersion),
         max(cohort.nettotal),
         max(cohort.outputTotal),
         max(cohort.dialysistotal),
         max(cohort.labresultoffset),
         max(cohort.labtypeid),
         max(cohort.labresult),
         max(cohort.labresulttext),
         max(cohort.labresultrevisedoffset),
max(vital.observationoffset) as observationoffset
,	max(vital.temperature) as temperature,
max(vital.sao2) as sao2,	max(vital.heartrate) as heartrate,	max(vital.respiration) as respiration,	max(vital.cvp) as cvp,	max(vital.etco2) as etco2,	
max(vital.systemicsystolic) as systemicsystolic,	max(vital.systemicdiastolic) as systemicdiastolic,	max(vital. systemicmean) as systemicmean,
max(vital.pasystolic) as pasystolic,	max(vital.padiastolic) as padiastolic,	max(vital.pamean) as pamean,	
max(vital.st1) as st1,	max(vital.st2) as st2,	max(vital.st3) as st3,	max(vital.icp) as vital,
max(resp.airwaytype) as airwaytype,
max(hist.pasthistorynotetype) as pasthistorynotetype,	max(hist.pasthistorypath) as pasthistorypath,	max(hist.pasthistoryvalue) as pasthistoryvalue,	max(hist.pasthistoryvaluetext) as pasthistoryvaluetext 
from `AED_effect_seizure.eICU_cohort3` cohort 
left outer join `physionet-data.eicu_crd.vitalperiodic` vital 
on vital.patientunitstayid = cohort.patientunitstayid
left outer join `physionet-data.eicu_crd.respiratorycare` resp
on resp.patientunitstayid = cohort.patientunitstayid
left outer join `physionet-data.eicu_crd.pasthistory` hist 
on hist.patientunitstayid = cohort.patientunitstayid
group by cohort.patientunitstayid