WITH ALLGCS as 
  (SELECT D.SUBJECT_ID, DATE_DIFF(DATE(HADM.ADMITTIME), DATE(P.DOB), YEAR) as age, P.GENDER, ICD.ICD9_CODE, 
  ICD.SHORT_TITLE, HADM.DIAGNOSIS, HADM.ADMITTIME, HADM.DISCHTIME,  HADM.DEATHTIME, 
  CASE WHEN CH.ITEMID in (723,223900) THEN valuenum ELSE -1 END AS GCSVerbal,
  CASE WHEN CH.ITEMID in (454,223901) THEN valuenum ELSE -1 END AS GCSMotor,
  CASE WHEN CH.ITEMID in (184,220739) THEN valuenum ELSE -1 END AS GCSEyes,
  CH.valuenum, D.HADM_ID
  FROM `physionet-data.mimiciii_clinical.d_icd_diagnoses`  ICD 
  INNER JOIN `physionet-data.mimiciii_clinical.diagnoses_icd`  D 
  ON ICD.ICD9_CODE = D.ICD9_CODE
  INNER JOIN `physionet-data.mimiciii_clinical.admissions` HADM
  ON HADM.HADM_ID = D.HADM_ID 
  INNER JOIN `physionet-data.mimiciii_clinical.patients` P 
  ON HADM.SUBJECT_ID = P.SUBJECT_ID 
  LEFT OUTER JOIN `physionet-data.mimiciii_clinical.chartevents` CH 
  ON CH.HADM_ID = HADM.HADM_ID 
  AND CH.SUBJECT_ID = P.SUBJECT_ID
  AND CH.ITEMID in (184, 454, 723, 223900, 223901, 220739) -- Item ids corresponding to the GCS 
  AND DATE_DIFF(DATE(CH.CHARTTIME), DATE(HADM.ADMITTIME), DAY) < 3
  WHERE ICD.ICD9_CODE LIKE '85%')
SELECT SUBJECT_ID, age, GENDER, ICD9_CODE, 
  SHORT_TITLE, DIAGNOSIS, ADMITTIME, DISCHTIME,  DEATHTIME, max(GCSVerbal) as GCSVerbal,max(GCSMotor) as GCSMotor,max(GCSEyes) as GCSEyes, HADM_ID
FROM ALLGCS
GROUP BY SUBJECT_ID, age, GENDER, ICD9_CODE, 
  SHORT_TITLE, DIAGNOSIS, ADMITTIME, DISCHTIME,  DEATHTIME, HADM_ID